# Generated by Django 4.0.6 on 2024-04-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensinosuperior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='cursos',
            field=models.ManyToManyField(related_name='cursos', to='ensinosuperior.curso'),
        ),
    ]
