# Generated by Django 4.0.6 on 2024-04-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensinosuperior', '0002_disciplina_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='area_cientifica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='ensinosuperior.areacientifica'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='cursos',
            field=models.ManyToManyField(related_name='disciplinas', to='ensinosuperior.curso'),
        ),
    ]
