# Generated by Django 4.0.6 on 2024-03-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='ano_de_criacao',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
