# Generated by Django 4.0.6 on 2024-04-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_banda_ano_de_criacao_banda_nacionalidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='banda',
            old_name='ano_de_criacao',
            new_name='ano_criacao',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='duracao_segundos',
        ),
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.CharField(default='0', max_length=10, verbose_name='Duração'),
        ),
    ]
