# Generated by Django 4.0.6 on 2024-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_musica_letra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='link_spotify',
            field=models.URLField(blank=True, null=True),
        ),
    ]
