# Generated by Django 4.0.6 on 2024-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descricao',
            field=models.TextField(default=' ', verbose_name='Descrição'),
        ),
    ]
