# Generated by Django 4.0.6 on 2024-03-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_comentario_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, null=True),
        ),
    ]
