# Generated by Django 4.0.6 on 2024-03-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_artigo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
